const {upgradeProxy} = require('@openzeppelin/truffle-upgrades');
const CharacterStaking = artifacts.require('CharacterStaking');
const WeaponStaking = artifacts.require('WeaponStaking');
const KingStaking = artifacts.require('KingStaking');
const Village = artifacts.require('Village');
module.exports = async function (deployer) {
  await upgradeProxy(Village.address, Village, {deployer});
  await upgradeProxy(CharacterStaking.address, CharacterStaking, {deployer});
  await upgradeProxy(WeaponStaking.address, WeaponStaking, {deployer});
  const kingStaking = await upgradeProxy(KingStaking.address, KingStaking, {deployer});
  await kingStaking.addStake(1, 6, web3.utils.toWei('1', 'ether'));
  await kingStaking.addStake(2, 12, web3.utils.toWei('2', 'ether'));
  await kingStaking.addStake(3, 18, web3.utils.toWei('3', 'ether'));
  await kingStaking.addStake(4, 24, web3.utils.toWei('4', 'ether'));
  await kingStaking.addStake(5, 30, web3.utils.toWei('5', 'ether'));
  await kingStaking.addStake(6, 60, web3.utils.toWei('10', 'ether'));
  await kingStaking.addStake(7, 120, web3.utils.toWei('12', 'ether'));
  await kingStaking.addStake(8, 180, web3.utils.toWei('14', 'ether'));
  await kingStaking.addStake(9, 240, web3.utils.toWei('18', 'ether'));
  await kingStaking.addStake(10, 300, web3.utils.toWei('20', 'ether'));
  await kingStaking.addStake(11, 420, web3.utils.toWei('23', 'ether'));
  await kingStaking.addStake(12, 600, web3.utils.toWei('26', 'ether'));
  await kingStaking.addStake(13, 780, web3.utils.toWei('29', 'ether'));
  await kingStaking.addStake(14, 960, web3.utils.toWei('32', 'ether'));
  await kingStaking.addStake(15, 1140, web3.utils.toWei('35', 'ether'));
  await kingStaking.addStake(16, 1380, web3.utils.toWei('40', 'ether'));
  await kingStaking.addStake(17, 1680, web3.utils.toWei('45', 'ether'));
  await kingStaking.addStake(18, 2040, web3.utils.toWei('50', 'ether'));
  await kingStaking.addStake(19, 2400, web3.utils.toWei('55', 'ether'));
  await kingStaking.addStake(20, 3000, web3.utils.toWei('60', 'ether'));
};
